name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 1.8.0_202

      - name: Build application
        run: javac C:/Users/PCS/Desktop/Cr_Devops_Maatallah_Meriam/*.java -d C:/Users/PCS/Desktop/Cr_Devops_Maatallah_Meriam/out

  test:
    name: Test
    runs-on: windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 1.8.0_202

      - name: Run automated tests
        run: java -cp C:\Users\PCS\Desktop\Cr_Devops_Maatallah_Meriam\out;C:\Users\PCS\Desktop\Cr_Devops_Maatallah_Meriam\lib org.junit.runner.JUnitCore TaskManagerTest

  deployment:
    name: Deployment
    runs-on: windows
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 1.8.0_202

      - name: Deploy to production
        run: |
          docker build -t my-app .
          docker run -d -p 8080:8080 my-app
